variables:
  DEBFULLNAME: "Salsa Pipeline"
  DEBEMAIL: "<salsa-pipeline@debian.org>"
  DEBIAN_FRONTEND: noninteractive
  WORKING_DIR: ./debian/output

stages:
  - build
  - test

image: debian:unstable

build package:
  stage: build
  artifacts:
    expire_in: 10 day
    name: "$CI_BUILD_NAME"
    paths:
        - ${WORKING_DIR}/
  script:
    - apt-get update
    - apt-get install eatmydata -y
    - eatmydata apt-get build-dep -y .
    - eatmydata apt-get install git-buildpackage -y
    - gbp pull --ignore-branch
    - if ! git rev-parse --verify 'pristine-tar' > /dev/null 2>&1 ; then
      git rev-parse --verify 'origin/pristine-tar' > /dev/null 2>&1 &&
      git fetch origin pristine-tar:pristine-tar ;
      fi
    - gbp buildpackage --git-ignore-branch --git-export-dir=${WORKING_DIR} -us -uc

run autopkgtest:
  stage: test
  script:
    - apt-get update && apt-get install autopkgtest eatmydata -y --no-install-recommends
    - 'if [ -d ./debian/tests ] ; then
      eatmydata autopkgtest ${WORKING_DIR}/*.deb -- null ;
      else
      echo "WARNING: No autopkgtest directory found, test run skipped!" ;
      fi'

run lintian:
  stage: test
  script:
    - apt-get update && apt-get install lintian -y --no-install-recommends
    - lintian -iI ${WORKING_DIR}/*.changes

run piuparts:
  stage: test
  script:
    - apt-get update && apt-get install piuparts eatmydata -y
    - piuparts -d sid -m http://deb.debian.org/debian/ ${WORKING_DIR}/*.changes
  tags:
    - privileged
